print("********Caixa rapida*********")
print("Bienvenidas a mi Super")
print("Data: 27.02 Tiempo: 13.46")
respo = input("Como se llama el trabajador?")
nombre = int(respo)
print("Te sirvió el trabajador", nombre)
resposta = input("Primero precio: ")
resposta1 = int(resposta)
respost = input("Segundo precio: ")
resposta2 = int(respost)
respos = input("Terceiro precio: ")
resposta3 = int(respos)
print("En total tienes que pagar:", resposta1+resposta2+resposta3, "euros")
print("Gracias, por venir, te esperemos más")
print("Con nuestro super tus compras pueden ser más rapidas, faciles y comodas!!!")
print("Si te gusta nuestro super, puedes compartir este enlace a tus amigos)")
print("misuper.com/htppt")